### ISSUE TITLE
Use prettyci instead of travis based style checks

### ISSUE THREAD

**Issue by staabm** [ergebnis/composer-normalize#90]
Using prettyci for the stylechecks can free a single travis job and also leads to a faster feedback loop (as far as style checks is a concern).

Another usefull sideeffect is a simpler travis.yml

See https://prettyci.com/ which is free for open source projects

**Comment by localheinz** [comment]
@staabm

Thank you for your suggestion!

However, following my argumentation on [r/PHP: Just released a project called PrettyCI that runs php-cs-fixer and CodeSniffer as a service: feedback welcome!](https://www.reddit.com/r/PHP/comments/95uh0q/just_released_a_project_called_prettyci_that_runs/) I don't actually find this very useful.

For a moment, let's just think about scenarios for the current repository, and let's also ignore that we use AppVeyor, where builds are apparently run in sequence (or only one build at a time is allowed) and consequently take ages, thus constitute a bottleneck.

In this repository, we have a multi-stage build on Travis CI with the following stages:

* `cs` (1 build)
* `stan` (1 build)
* `test` (currently 6 builds, when PHP 7.3 stable is released 9 builds, all of which could be run in parallel, but are limited to the number of parallel builds Travis CI allows for open source repositories)
* `infection` (1 build)

Builds of a subsequent stage are only run when all builds of the current stage have passed.

Since PrettyCI is only concerned with providing feedback in regard to code style, let’s assume scenarios where a commit is pushed, and all tests will pass:

1. the code style follows the configured style (*code style ok*)
2. the code style does not follow the configured style (*code style not ok*)

### Without PrettyCI

#### Code style ok

* `cs` (1 build)
* `stan` (1 build)
* `test` (6 builds)
* `infection` (1 build)

In total, **9 builds** will be run on Travis CI.

#### Code style not ok

* `cs` (1 build)

In total, **1 build** will be run on Travis CI, and since it fails, none of the other builds will run.

### With PrettyCI

#### Code style ok

* `stan` (1 build)
* `test` (6 builds)
* `infection` (1 build)

In total, **8 builds** will be run on Travis CI, and 1 build on PrettyCI. 

:bulb: In a success scenario, we save 1 build on Travis CI and have faster feedback through PrettyCI. Regardless, we still need to wait for all builds to pass.

#### Code style not ok

* `stan` (1 build)
* `test` (6 builds)
* `infection` (1 build)

In total, **8 builds** will be run on Travis CI, and 1 build on PrettyCi.

:bulb: In a failure scenario, instead of 1 build we run 8 builds on Travis CI (and all of them are more costly).

Not sure what I am missing, but personally, I don't find it useful or resourceful. 

In addition, as I have pointed out in [Makefile for lazy developers](https://localheinz.com/blog/2018/01/24/makefile-for-lazy-developers/), I believe build tools should also be run by any developer locally, and the feedback there is immediate. As suggested in [`CONTRIBUTING.md`](https://github.com/localheinz/composer-normalize/blob/master/.github/CONTRIBUTING.md#extra-lazy), the fastest feedback is provided by running

```
$ make
```

locally.

What do you think?

**Comment by staabm** [comment]
First, let me thank you for the exhaustive feedback.

I dont think CS is something which should be handled by the PR author, but the maintainer.
For that reason I dont think it makes sense to skip the unit tests, static analysis etc. because of a failing CS check.
Commits to fix CS should skip regular (travis) builds as CS shouldnt affect functionality.

Furthermore I feel like we will have e.g. phpstan run as a separate service in the near future

I agree with your point though, that there are other alternatives which could also be used (circleci or similar).

Feel free to stay with your setup in case you dont agree. Thats perfectly fine.

**Comment by localheinz** [comment]
Thank you, @staabm!

 I might reconsider at a later time!
